### ISSUE TITLE
FR: Random Colors

### ISSUE THREAD

**Issue by mesqueeb** [open-cli-tools/concurrently#279]
is there anyway to just add the `--color` without defining colors for random colors?

**Comment by gustavohenke** [comment]
I like the idea! Could be useful. PRs are welcome 😄

**Comment by gustavohenke** [comment]
Published in v7.5.0!

**Comment by mesqueeb** [comment]
@gustavohenke what's the final syntax landed on ?

**Comment by paescuj** [comment]
@mesqueeb See https://github.com/open-cli-tools/concurrently#usage or `concurrently -h`.

**Comment by mesqueeb** [comment]
`concurrently -c auto`

**Comment by paescuj** [comment]
> `concurrently -c auto`

Basically, yeah. However, it's important to understand that this is based on the fact that "If there are more commands than colors, the last color will be repeated." In this case `auto` will be repeated for every command.
And `auto` can be mixed with statically defined colors, e.g. `red,auto` or `red,auto,blue`.
That's why I referenced to https://github.com/open-cli-tools/concurrently#usage.
