### ISSUE TITLE
Wildcard option doesn't seem to follow README

### ISSUE THREAD

**Issue by TigersWay** [open-cli-tools/concurrently#312]
Despite #212, it seems the wildcard option still (v7.x) doesn't get `name` right, 
> concurrently "npm:watch-*"
> 
> Equivalent to:
> concurrently -n js,css,node "npm run watch-js" "npm run watch-css" "npm run watch-node"

but gives now:
`concurrently -n watch-*js,watch-*css,watch-*node "npm run watch-js" "npm run watch-css" "npm run watch-node"`

Something I understood wrong or a recurring bug?

**Comment by AmmarArnt** [comment]
Getting the same behaviour with 7.1.0

It seems that naming got broken.

**Comment by gustavohenke** [comment]
Might be one way of fixing this.
When a command's name contains wildcards, it's replaced there too.

To make the problem more apparent, you can try running the command line `concurrently -n wild-west-* "npm:watch-*"`.
- **Currently/before**, it gets translated to `concurrently -n wild-west-*js,wild-west-*css "npm run watch-js" "npm run watch-css"`
- **After**, it would be translated to `concurrently -n wild-west-js,wild-west-css "npm run watch-js" "npm run watch-css"`.

Any thoughts?

**Comment by TigersWay** [comment]
@gustavohenke I would love not to be the only one answering 😊 .... But i think I could use it that way!
What about then `concurrently -n * "npm:watch-*"`?

**Comment by gustavohenke** [comment]
That's exactly what I've suggested 👍 

Mind you, this change will be a breaking change as it turns `*` into a special character for `-n`.

**Comment by gkweb** [comment]
I'm having the same issue here. I ended up just manually inputing the commands with no wildcards.

**Comment by justmoon** [comment]
If you don't mind a little jank, you can use this as a workaround:
```
concurrently -n '​' 'npm:watch-*'
```

There is a [zero-width space character](https://en.wikipedia.org/wiki/Zero-width_space) being passed as the argument to `-n`. So this will only work if you copy/paste the above. It won't work if you try to type it in without the ZWS.

**Comment by patrickfatrick** [comment]
Hi, trying out concurrently and came across this issue rather immediately because I happen to use wildcards liberally (currently using npm-run-all which also supports wildcards). passing `-n` is a workaround (ie `concurrently -n build: \"npm:build:*\"` is equivalent `concurrently -n build:server,build:client \"npm:build:*\"`). However the description in #211 is IMO not what should happen when `-n` is not passed. It should match the name of the script in package.json, not the wildcard contents (ie `build:js` not `js`).

**Comment by paescuj** [comment]
Since this annoys me as well, I'm going to fix it!

I think the way it is described in the README really makes sense, therefore my suggestion is to simply adjust the implementation to match this behavior:
```json
  "scripts": {
    "lint:js": "echo js",
    "lint:ts": "echo ts",
  }
```
```shell
concurrently "npm:lint:*"
```
Will result in:
```console
...
[js] js
[ts] ts
...
```

As an alternative, I think we could also just use the name of the matching script, which in that case will result in:
```console
...
[lint:js] js
[lint:ts] ts
...
```
(However, with this approach the "prefixing" as described in the README would no longer make sense)

Please let me know, which solution you prefer! Thanks!

**Comment by patrickfatrick** [comment]
You're right, the readme does stipulate that behavior here

```
concurrently "npm:watch-*"

# Equivalent to:
concurrently -n js,css,node "npm run watch-js" "npm run watch-css" "npm run watch-node"
```

Personally I don't think that's really any better than showing the full script name like so

```
concurrently "npm:watch-*"

# Equivalent to:
concurrently -n watch-js,watch-css,watch-node "npm run watch-js" "npm run watch-css" "npm run watch-node"
```

However I will also say that it's easier to add the `watch-` prefix via `-n` arg than it is to remove it for users who DO only want to show the wildcard-matched string. So, either way, I guess.

**Comment by paescuj** [comment]
Thanks @patrickfatrick! I really appreciate your feedback on this!

I agree that both solution do come with a few drawbacks and thus realized that it might be worth starting a discussion in a separate tread to find a better solution.
However, since this issue here is valid as `concurrently` indeed doesn't behavior like described in the README, I decided to focus on fixing this, for now.

**Comment by patrickfatrick** [comment]
@paescuj awesome, that was quick. Look forward to its release.
